servers:
  - name: local_weather
    command: python
    venv: .venv   # relative project venv
    args:
      - 3.MCP/mcp_server.py
    enabled: true
  - name: local_search
    command: python
    venv: .venv
    args:
      - 3.MCP/mcp_search_server.py
    enabled: true
  - name: playwright_browser
    command: python
    venv: .venv
    args:
      - 3.MCP/mcp_playwright_server.py
    enabled: true
